// WARNING: This file has automatically been generated on Fri, 21 Jul 2023 13:47:56 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "xdxml.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

