// WARNING: This file has automatically been generated on Mon, 06 May 2024 15:54:15 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "xdxml.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

