// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types.go

package xdxml

type Node_path struct {
	Card               [128]int8
	Hwmon              [128]int8
	Name               [256]int8
	Dbdf               [256]int8
	Current_link_speed [256]int8
	Current_link_width [256]int8
	Max_link_speed     [256]int8
	Max_link_width     [256]int8
}

type Device struct {
	Handle *_Ctype_struct_xdx_device_st
}

type Pci_info struct {
	Domain   uint64
	Bus      uint64
	Device   uint64
	Bdfid    uint64
	Func     uint64
	Pci_dbdf [64]int8
	Bus_id   [32]int8
}
